// File: app/layout.js (VERSI PERBAIKAN)

import localFont from "next/font/local";
import "./globals.css";
import ClientProviders from "../../components/ClientProviders"; // Cukup import ini

const poppins = localFont({
  src: [
    { path: "../../public/fonts/Poppins-Regular.ttf", weight: "400" },
    { path: "../../public/fonts/Poppins-Medium.ttf", weight: "500" },
    { path: "../../public/fonts/Poppins-SemiBold.ttf", weight: "600" },
    { path: "../../public/fonts/Poppins-Bold.ttf", weight: "700" },
  ],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${poppins.variable} font-poppins antialiased`}
      >
        <ClientProviders>
          {children}
        </ClientProviders>
      </body>
    </html>
  );
}